name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies
      env:
        GO111MODULE: auto
      run: |
        go get -v -t -d ./...

    - name: Test
      run: |
        go test -cpu=2 -race -v ./...
        go test -cpu=2 -covermode=atomic ./...

    - name: Run vet
      run: |
        go vet ./...

    - name: Build
      run: go build -v ./...
